spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photoDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



