spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photoDB?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.enable_lazy_load_no_trans: true
      hibernate:
        ddl-auto: update
